### ISSUE TITLE
Bug in network_cli

### ISSUE THREAD

**Issue by 2Max4** [2Max4/Network_Analysis#41]
Error occurs when running network_cli.py - First guess could be that something with multi threating is not working properly.

```Traceback (most recent call last):
  File "network_cli.py", line 19, in <module>
    Thread(target=email_report.send_weekly_report())
  File "\Network_Analysis\send_email.py", line 96, in send_weekly_report
    schedule.every().monday.at("07:30").do(self.send_email())
  File "AppData\Local\Continuum\anaconda3\lib\site-packages\schedule\__init__.py", line 440, in do
    self.job_func = functools.partial(job_func, *args, **kwargs)
TypeError: the first argument must be callable
```

**Comment by 2Max4** [comment]
See PR #43
